-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBIuufakQ28n9CmzjEGV+G0UFhUXZL+X/H0gQ+KFVkNCAAAAKDFTJdKxUyX
SgAAAAtzc2gtZWQyNTUxOQAAACBIuufakQ28n9CmzjEGV+G0UFhUXZL+X/H0gQ+KFVkNCA
AAAEDA6I53MFex+zMevPJJnkvfFSWFbmibGQPqHZTo/3X9u0i659qRDbyf0KbOMQZX4bRQ
WFRdkv5f8fSBD4oVWQ0IAAAAHGx1a2Fzemtvd2FsZXdza2lAZXhhbXBsZS5jb20B
-----END OPENSSH PRIVATE KEY-----
